services:
  backend:
    build: ./backend
    ports:
      - '9006:9006'
    env_file:
      - ./backend/.env
    restart: unless-stopped
    environment:
      - PORT=9006

  frontend:
    build: ./frontend
    ports:
      - '9007:9007'
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    environment:
      - PORT=9007
